/**
 * Photos for the "Built by kids like yours" wall on the homepage.
 *
 * Hand-picked from each product page's "See What Others Are Creating" gallery
 * (and, for Blockaroo, its product image folders) — genuine social-proof shots
 * of kids, hands and finished builds. Every entry ties back to a real product
 * `handle` so the flip side can link to the kit.
 *
 * Curation rules (this file is generated to keep them honest):
 *  - Even spread across products: at most 2 photos per product, so no single
 *    product dominates a brand.
 *  - No duplicate photos: selection is de-duplicated by image content (md5);
 *    the same product may appear more than once with genuinely different shots.
 *  - `width`/`height` are the real source pixels (drives the masonry aspect).
 *
 * The wall interleaves by brand and shows ~12 at a time (see CustomerPhotoWall).
 */
export type WallPhotoSource = {
  handle: string;
  brand: string;
  src: string;
  alt: string;
  width: number;
  height: number;
};

export const WALL_PHOTOS: WallPhotoSource[] = [
  // Snap Circuits
  {
    handle: "snap-circuits-arcade",
    brand: "snap-circuits",
    src: "/images/products/snap-circuits-arcade/child-playing-with-arcade.jpeg",
    alt: "Child engaged and playing with the assembled Snap Circuits Arcade",
    width: 1200,
    height: 900,
  },
  {
    handle: "snap-circuits-beginner",
    brand: "snap-circuits",
    src: "/images/products/snap-circuits-beginner/fingers-pressing-switches-in-dark-with-lights.jpg",
    alt: "Fingers pressing switches on Snap Circuits board with coloured lights glowing in the dark",
    width: 1200,
    height: 904,
  },
  {
    handle: "snap-circuits-classic-300",
    brand: "snap-circuits",
    src: "/images/products/snap-circuits-classic-300/child-building-circuit.jpg",
    alt: "Child's hands actively building a Snap Circuits project on a wooden table",
    width: 962,
    height: 2079,
  },
  {
    handle: "snap-circuits-explorer-junior",
    brand: "snap-circuits",
    src: "/images/products/snap-circuits-explorer-junior/child-building-board-with-manual-in-front-of-him.jpg",
    alt: "Child building a Snap Circuits Explorer Junior project with the manual open in front of them",
    width: 1224,
    height: 1632,
  },
  {
    handle: "snap-circuits-my-home",
    brand: "snap-circuits",
    src: "/images/products/snap-circuits-my-home/hands-snapping-pieces-together.jpeg",
    alt: "Hands snapping circuit pieces together on the board",
    width: 1200,
    height: 900,
  },
  {
    handle: "snap-circuits-arcade",
    brand: "snap-circuits",
    src: "/images/products/snap-circuits-arcade/arcade-built-on-counter.jpg",
    alt: "Snap Circuits Arcade fully assembled on a kitchen counter",
    width: 1280,
    height: 720,
  },
  {
    handle: "snap-circuits-beginner",
    brand: "snap-circuits",
    src: "/images/products/snap-circuits-beginner/kid-playing-with-board.jpg",
    alt: "Child playing with the Snap Circuits Beginner board",
    width: 1200,
    height: 1159,
  },
  {
    handle: "snap-circuits-classic-300",
    brand: "snap-circuits",
    src: "/images/products/snap-circuits-classic-300/circuits-built-on-the-floor.jpg",
    alt: "Completed Snap Circuits AM radio project built on the floor",
    width: 1632,
    height: 1224,
  },
  {
    handle: "snap-circuits-my-home",
    brand: "snap-circuits",
    src: "/images/products/snap-circuits-my-home/close-up-of-side-of-home.jpeg",
    alt: "Side view of a Snap Circuits My Home build",
    width: 600,
    height: 800,
  },

  // National Geographic
  {
    handle: "national-geographic-build-your-own-volcano",
    brand: "national-geographic",
    src: "/images/products/national-geographic-build-your-own-volcano/boy-stirring-volcano-mix.jpg",
    alt: "Boy stirring volcano plaster mix",
    width: 493,
    height: 493,
  },
  {
    handle: "national-geographic-crystal-garden",
    brand: "national-geographic",
    src: "/images/products/national-geographic-crystal-garden/boy-holding-pen-to-colour-tree.jpg",
    alt: "Boy holding a marker, about to colour his crystal tree",
    width: 1200,
    height: 1200,
  },
  {
    handle: "national-geographic-dino-fossil-dig-kit",
    brand: "national-geographic",
    src: "/images/products/national-geographic-dino-fossil-dig-kit/kids-scraping-at-fossil.png",
    alt: "Kids carefully scraping at a fossil dig brick",
    width: 1200,
    height: 1200,
  },
  {
    handle: "national-geographic-epic-circuits-science-kit",
    brand: "national-geographic",
    src: "/images/products/national-geographic-epic-circuits-science-kit/end-user-child-playing.jpg",
    alt: "Child experimenting with the National Geographic Epic Circuits kit",
    width: 588,
    height: 588,
  },
  {
    handle: "national-geographic-glow-in-the-dark-human-body",
    brand: "national-geographic",
    src: "/images/products/national-geographic-glow-in-the-dark-human-body/childs-hands-putting-body-together.jpg",
    alt: "Child's hands carefully assembling the human body model",
    width: 1414,
    height: 1414,
  },
  {
    handle: "national-geographic-glow-in-the-dark-solar-system-activity-kit",
    brand: "national-geographic",
    src: "/images/products/national-geographic-glow-in-the-dark-solar-system-activity-kit/child-painting.jpg",
    alt: "Child carefully painting a planet from the solar system kit",
    width: 1200,
    height: 1232,
  },
  {
    handle: "national-geographic-mega-bug-habitat",
    brand: "national-geographic",
    src: "/images/products/national-geographic-mega-bug-habitat/girl-in-garden-looking-through-magnifying-glass.png",
    alt: "Girl in garden looking through magnifying glass at insects",
    width: 1200,
    height: 1200,
  },
  {
    handle: "national-geographic-motorized-marble-run",
    brand: "national-geographic",
    src: "/images/products/national-geographic-motorized-marble-run/marble-run-built-with-kids-inthe-background.jpg",
    alt: "A completed marble run configuration with children visible in the background",
    width: 527,
    height: 527,
  },
  {
    handle: "national-geographic-build-your-own-volcano",
    brand: "national-geographic",
    src: "/images/products/national-geographic-build-your-own-volcano/child-painting-volcano-with-box-in-front.jpg",
    alt: "Child painting their volcano with the kit box in front",
    width: 500,
    height: 500,
  },
  {
    handle: "national-geographic-crystal-garden",
    brand: "national-geographic",
    src: "/images/products/national-geographic-crystal-garden/trees-growing.jpg",
    alt: "Two crystal trees covered in growing crystals in their chosen colours",
    width: 1200,
    height: 1200,
  },
  {
    handle: "national-geographic-dino-fossil-dig-kit",
    brand: "national-geographic",
    src: "/images/products/national-geographic-dino-fossil-dig-kit/fossil-smashed.png",
    alt: "Excavated fossil specimen from the dig kit",
    width: 1200,
    height: 1200,
  },
  {
    handle: "national-geographic-epic-circuits-science-kit",
    brand: "national-geographic",
    src: "/images/products/national-geographic-epic-circuits-science-kit/end-user-building-circuits.jpg",
    alt: "Child building circuits with the Epic Circuits kit",
    width: 800,
    height: 800,
  },

  // MatataStudio
  {
    handle: "matatastudio-coding-set-pro",
    brand: "matatastudio",
    src: "/images/products/matatastudio-coding-set-pro/2-boys-playing-together-on-floor.jpg",
    alt: "Two boys collaborating on coding challenges",
    width: 1200,
    height: 787,
  },
  {
    handle: "matatastudio-coding-set-pro-classroom-set",
    brand: "matatastudio",
    src: "/images/products/matatastudio-coding-set-pro-classroom-set/kids-playing-together.jpg",
    alt: "Two learners working together on a MatataStudio coding challenge",
    width: 1200,
    height: 900,
  },
  {
    handle: "matatastudio-digital-microscope-mt3-2",
    brand: "matatastudio",
    src: "/images/products/matatastudio-digital-microscope-mt3-2/screening-something-with-hand-holding-base.png",
    alt: "Hand holding a specimen base while observing under the microscope",
    width: 800,
    height: 800,
  },
  {
    handle: "matatastudio-digital-microscope-mx2-as",
    brand: "matatastudio",
    src: "/images/products/matatastudio-digital-microscope-mx2-as/microscope-scanning-orange-peel.jpg",
    alt: "MX2-AS digital microscope scanning the surface of an orange peel",
    width: 1200,
    height: 1600,
  },
  {
    handle: "matatastudio-nous-ai-set",
    brand: "matatastudio",
    src: "/images/products/matatastudio-nous-ai-set/image-of-bot.jpg",
    alt: "Nous AI robot on desk",
    width: 1200,
    height: 904,
  },
  {
    handle: "matatastudio-tale-bot-pro",
    brand: "matatastudio",
    src: "/images/products/matatastudio-tale-bot-pro/kids-in-hall-afterclass-playing-with-talebot-pro.png",
    alt: "Children playing with Tale-Bot Pro in a classroom setting",
    width: 800,
    height: 800,
  },
  {
    handle: "matatastudio-tale-bot-pro-classroom-set",
    brand: "matatastudio",
    src: "/images/products/matatastudio-tale-bot-pro-classroom-set/lots-of-kids-gathered-around-playing.jpeg",
    alt: "Large group of young learners gathered around Tale-Bot Pro robots in a classroom",
    width: 1200,
    height: 582,
  },
  {
    handle: "matatastudio-vincibot-classroom-set",
    brand: "matatastudio",
    src: "/images/products/matatastudio-vincibot-classroom-set/kids-watching-vincibot-draw.jpeg",
    alt: "Kids watching VinciBot draw with a marker",
    width: 800,
    height: 592,
  },
  {
    handle: "matatastudio-vincibot-coding-robot-set",
    brand: "matatastudio",
    src: "/images/products/matatastudio-vincibot-coding-robot-set/child-coding-on-laptop-with-vincibot-next-to-her-on-built-pathway.png",
    alt: "Child coding on laptop with VinciBot on a pathway",
    width: 830,
    height: 542,
  },
  {
    handle: "matatastudio-coding-set-pro",
    brand: "matatastudio",
    src: "/images/products/matatastudio-coding-set-pro/3-kids-playing-together.jpeg",
    alt: "Three children working together with MatataStudio",
    width: 1200,
    height: 810,
  },
  {
    handle: "matatastudio-coding-set-pro-classroom-set",
    brand: "matatastudio",
    src: "/images/products/matatastudio-coding-set-pro-classroom-set/girl-playing.jpg",
    alt: "Girl independently placing coding blocks on the control board",
    width: 1200,
    height: 1199,
  },
  {
    handle: "matatastudio-digital-microscope-mt3-2",
    brand: "matatastudio",
    src: "/images/products/matatastudio-digital-microscope-mt3-2/microscope-screening-petridish.png",
    alt: "Microscope observing a petri dish specimen",
    width: 800,
    height: 800,
  },

  // Makerzoid
  {
    handle: "makerzoid-diverse-building-blocks",
    brand: "makerzoid",
    src: "/images/products/makerzoid-diverse-building-blocks/hands-clicking-on-tablet-screen-with-box-in-front.jpg",
    alt: "Child using the Makerzoid app on a tablet with the product box in front",
    width: 800,
    height: 802,
  },
  {
    handle: "makerzoid-robot-master-premium",
    brand: "makerzoid",
    src: "/images/products/makerzoid-robot-master-premium/two-kids-playing-together-building-and-with-app-on-phone.png",
    alt: "Two kids building together with Makerzoid and app on phone",
    width: 783,
    height: 839,
  },
  {
    handle: "makerzoid-robot-master-tournament",
    brand: "makerzoid",
    src: "/images/products/makerzoid-robot-master-tournament/robot-on-track-competition.png",
    alt: "Makerzoid robot positioned on a competition track",
    width: 1080,
    height: 1080,
  },
  {
    handle: "makerzoid-smart-robot",
    brand: "makerzoid",
    src: "/images/products/makerzoid-smart-robot/build-car-robot.jpg",
    alt: "Completed car robot build",
    width: 1200,
    height: 900,
  },
  {
    handle: "makerzoid-smart-robot-premium",
    brand: "makerzoid",
    src: "/images/products/makerzoid-smart-robot-premium/end-user-5.jpg",
    alt: "Hands sorting and organising building pieces",
    width: 1200,
    height: 710,
  },
  {
    handle: "makerzoid-superbot",
    brand: "makerzoid",
    src: "/images/products/makerzoid-superbot/child-reaching-into-box-with-block-parts.jpg",
    alt: "Child's hands reaching into the Makerzoid Superbot storage box to pick out building pieces",
    width: 1200,
    height: 1108,
  },
  {
    handle: "makerzoid-superbot-master-premium",
    brand: "makerzoid",
    src: "/images/products/makerzoid-superbot-master-premium/distance-sensor-hand-in-front-of-robot.jpg",
    alt: "Child testing the distance sensor on an assembled Makerzoid Superbot",
    width: 800,
    height: 800,
  },
  {
    handle: "makerzoid-diverse-building-blocks",
    brand: "makerzoid",
    src: "/images/products/makerzoid-diverse-building-blocks/hand-holding-blocks-above-box-filled-with-blocks.jpg",
    alt: "Hand holding building blocks above a box filled with more pieces",
    width: 800,
    height: 800,
  },
  {
    handle: "makerzoid-robot-master-premium",
    brand: "makerzoid",
    src: "/images/products/makerzoid-robot-master-premium/crane-built-sitting-on-box-with-tablet-behind.png",
    alt: "Makerzoid crane build sitting on box with tablet behind",
    width: 756,
    height: 841,
  },
  {
    handle: "makerzoid-smart-robot",
    brand: "makerzoid",
    src: "/images/products/makerzoid-smart-robot/close-up-of-robot-build.jpg",
    alt: "Close-up detail of a completed robot build",
    width: 640,
    height: 1137,
  },
  {
    handle: "makerzoid-smart-robot-premium",
    brand: "makerzoid",
    src: "/images/products/makerzoid-smart-robot-premium/end-user-2.jpg",
    alt: "Collection of various robot builds created with the kit",
    width: 1200,
    height: 1851,
  },
  {
    handle: "makerzoid-superbot",
    brand: "makerzoid",
    src: "/images/products/makerzoid-superbot/car-built-with-pieces-around-it.jpg",
    alt: "Makerzoid Superbot orange racing car model built with spare bricks scattered around it",
    width: 1200,
    height: 1203,
  },

  // BBC micro:bit
  {
    handle: "bbc-micro-bit-club",
    brand: "bbc-microbit",
    src: "/images/products/bbc-micro-bit-club/kids-in-class-at-computers-with-microbit.jpg",
    alt: "Learners at computers in a classroom using micro:bit",
    width: 500,
    height: 511,
  },
  {
    handle: "bbc-micro-bit-go",
    brand: "bbc-microbit",
    src: "/images/products/bbc-micro-bit-go/end-user/kids-looking-at-amkecode-screen-holding-microbit.jpg",
    alt: "Two boys in a classroom looking at MakeCode on a laptop, one holding a micro:bit",
    width: 5199,
    height: 3495,
  },
  {
    handle: "micro-bit-wearable-x-10",
    brand: "bbc-microbit",
    src: "/images/products/micro-bit-wearable-x-10/kids-in-circle-with-straps-on-wrists.jpeg",
    alt: "Group of children in a circle each wearing a micro:bit wearable strap on their wrists",
    width: 1200,
    height: 675,
  },
  {
    handle: "bbc-micro-bit-club",
    brand: "bbc-microbit",
    src: "/images/products/bbc-micro-bit-club/two-kids-helping-each-other-makecode.jpg",
    alt: "Two learners helping each other with MakeCode on a micro:bit",
    width: 800,
    height: 600,
  },
  {
    handle: "bbc-micro-bit-go",
    brand: "bbc-microbit",
    src: "/images/products/bbc-micro-bit-go/end-user/two-kids-helping-eachother-with-makecode.jpg",
    alt: "A girl and boy sitting together at laptops, both working on MakeCode",
    width: 800,
    height: 600,
  },
  {
    handle: "micro-bit-wearable-x-10",
    brand: "bbc-microbit",
    src: "/images/products/micro-bit-wearable-x-10/kid-dancing-infront-of-projector-screen.jpg",
    alt: "Child dancing in front of a projector screen with a micro:bit wearable on their wrist",
    width: 1200,
    height: 1113,
  },

  // ELECFREAKS
  {
    handle: "elecfreaks-micro-bit-smart-cutebot-pro",
    brand: "elecfreaks",
    src: "/images/products/elecfreaks-micro-bit-smart-cutebot-pro/hand-plugging-in-microbit-with-cutebot-behind.jpg",
    alt: "Hand plugging a BBC micro:bit into the Cutebot Pro robot car",
    width: 800,
    height: 800,
  },
  {
    handle: "elecfreaks-micro-bit-tinker-kit",
    brand: "elecfreaks",
    src: "/images/products/elecfreaks-micro-bit-tinker-kit/plant-monitoring-device-example.jpg",
    alt: "Plant monitoring device built with the Tinker Kit showing moisture sensor in soil",
    width: 1200,
    height: 1200,
  },
  {
    handle: "elecfreaks-micro-bit-smart-cutebot-pro",
    brand: "elecfreaks",
    src: "/images/products/elecfreaks-micro-bit-smart-cutebot-pro/mans-hand-holding-cutebot-base-with-box-underneath.jpg",
    alt: "Hand holding the underside of the Cutebot Pro chassis with the box underneath",
    width: 800,
    height: 478,
  },
  {
    handle: "elecfreaks-micro-bit-tinker-kit",
    brand: "elecfreaks",
    src: "/images/products/elecfreaks-micro-bit-tinker-kit/open-kit.jpeg",
    alt: "ELECFREAKS Tinker Kit opened showing all the sensors and modules included",
    width: 1200,
    height: 1200,
  },

  // Arduino
  {
    handle: "arduino-iot-bundle",
    brand: "arduino",
    src: "/images/products/arduino-iot-bundle/arduiino-iot-connected.jpg",
    alt: "Arduino IoT Bundle board connected and sending data to the cloud",
    width: 1200,
    height: 899,
  },
  {
    handle: "arduino-sensor-kit-base",
    brand: "arduino",
    src: "/images/products/arduino-sensor-kit-base/kids-smiling-holding-sensor-base.jpg",
    alt: "Kids smiling while holding the Arduino Sensor Kit Base board",
    width: 1024,
    height: 927,
  },
  {
    handle: "arduino-starter-kit",
    brand: "arduino",
    src: "/images/products/arduino-starter-kit/finger-pressing-button-light-on.jpg",
    alt: "Finger pressing a button with LED lit up on an Arduino breadboard",
    width: 675,
    height: 900,
  },
  {
    handle: "arduino-student-kit",
    brand: "arduino",
    src: "/images/products/arduino-student-kit/teen-working-on-kit-with-workbook-and-laptop.jpg",
    alt: "Teen working on the Arduino Student Kit with workbook and laptop open",
    width: 1200,
    height: 800,
  },
  {
    handle: "arduino-iot-bundle",
    brand: "arduino",
    src: "/images/products/arduino-iot-bundle/board-connected-with-light-on.jpg",
    alt: "Arduino IoT Bundle board connected with LED indicator lit up",
    width: 1200,
    height: 899,
  },
  {
    handle: "arduino-sensor-kit-base",
    brand: "arduino",
    src: "/images/products/arduino-sensor-kit-base/pressing-button-with-oled-screen-on.png",
    alt: "Pressing the button module with the OLED screen displaying output",
    width: 1194,
    height: 700,
  },
  {
    handle: "arduino-starter-kit",
    brand: "arduino",
    src: "/images/products/arduino-starter-kit/uno-r3-plugged-into-breadboard.jpg",
    alt: "Arduino UNO R3 plugged into a breadboard with jumper wires",
    width: 675,
    height: 900,
  },
  {
    handle: "arduino-student-kit",
    brand: "arduino",
    src: "/images/products/arduino-student-kit/teen-homeschooling-with-student-kit.jpg",
    alt: "Teenager homeschooling with the Arduino Student Kit",
    width: 800,
    height: 800,
  },

  // NASA
  {
    handle: "nasa-astronaut-helmet",
    brand: "nasa",
    src: "/images/products/nasa-astronaut-helmet/child-dressed-in-astronaut-outfit.jpg",
    alt: "Child in white astronaut suit and NASA helmet giving two thumbs up",
    width: 1200,
    height: 1600,
  },
  {
    handle: "nasa-lunar-telescope",
    brand: "nasa",
    src: "/images/products/nasa-lunar-telescope/end-user-child-looking-through-telescope.jpg",
    alt: "Child looking through the NASA Lunar Telescope",
    width: 1060,
    height: 1885,
  },
  {
    handle: "nasa-moon-sand-activity-kit",
    brand: "nasa",
    src: "/images/products/nasa-moon-sand-activity-kit/boy-sitting-with-sand-box-in-front-of-him-holding-sand.jpg",
    alt: "Boy sitting with the NASA Moon Sand kit in front of him, holding moon sand",
    width: 1224,
    height: 1632,
  },
  {
    handle: "nasa-astronaut-helmet",
    brand: "nasa",
    src: "/images/products/nasa-astronaut-helmet/child-dressed-up-as-astronaut.jpg",
    alt: "Child in orange astronaut suit wearing the NASA helmet",
    width: 1200,
    height: 1600,
  },
  {
    handle: "nasa-lunar-telescope",
    brand: "nasa",
    src: "/images/products/nasa-lunar-telescope/end-user-girl-looking-through-scope.jpg",
    alt: "Girl independently using the NASA Lunar Telescope",
    width: 1298,
    height: 1541,
  },
  {
    handle: "nasa-moon-sand-activity-kit",
    brand: "nasa",
    src: "/images/products/nasa-moon-sand-activity-kit/hand-holding-moon-sand-above-sand-box.jpg",
    alt: "Hand holding a ball of moon sand above the play tray",
    width: 1224,
    height: 1632,
  },

  // Blockaroo
  {
    handle: "blockaroo-magnetic-foam-builders-airplane",
    brand: "blockaroo",
    src: "/images/products/blockaroo-magnetic-foam-builders-airplane/young-boy-playing-with-blocks.jpg",
    alt: "A young boy building with Blockaroo foam blocks",
    width: 1200,
    height: 1200,
  },
  {
    handle: "blockaroo-magnetic-foam-builders-castle",
    brand: "blockaroo",
    src: "/images/products/blockaroo-magnetic-foam-builders-castle/inspire-creativity.jpg",
    alt: "A creation built from Blockaroo magnetic foam blocks",
    width: 1200,
    height: 1004,
  },
  {
    handle: "blockaroo-magnetic-foam-builders-roadster",
    brand: "blockaroo",
    src: "/images/products/blockaroo-magnetic-foam-builders-roadster/three-kids-playing-with-blockaroo.jpg",
    alt: "Three kids playing with Blockaroo foam blocks",
    width: 1442,
    height: 1085,
  },
  {
    handle: "blockaroo-magnetic-foam-builders-robot",
    brand: "blockaroo",
    src: "/images/products/blockaroo-magnetic-foam-builders-robot/child-in-the-bath-with-blocks-laughing.jpg",
    alt: "A child laughing in the bath with Blockaroo foam blocks",
    width: 1200,
    height: 1034,
  },
  {
    handle: "blockaroo-magnetic-foam-builders-trunk-set",
    brand: "blockaroo",
    src: "/images/products/blockaroo-magnetic-foam-builders-trunk-set/child-building-with-blocks-in-the-bath.jpg",
    alt: "A child building with Blockaroo foam blocks in the bath",
    width: 1200,
    height: 875,
  },
  {
    handle: "blockaroo-magnetic-foam-builders-tug-boat",
    brand: "blockaroo",
    src: "/images/products/blockaroo-magnetic-foam-builders-tug-boat/kids-laughing-and-playing.jpg",
    alt: "Kids laughing and playing with Blockaroo foam blocks",
    width: 1200,
    height: 1200,
  },
];
